### ISSUE TITLE
version error

### ISSUE THREAD

**Issue by MareoRaft** [d-ying/string_truncate#1]
Hello!  I am interested in using your string truncator to truncate words on my website provemath.org.

I am not terribly familiar with Java.  I am running

    ~/Downloads/string_truncate-master % java -version
    java version "1.7.0_51"
    Java(TM) SE Runtime Environment (build 1.7.0_51-b13)
    Java HotSpot(TM) 64-Bit Server VM (build 24.51-b03, mixed mode)

I downloaded and unzipped your library, went into the folder and ran

    ~/Downloads/string_truncate-master % java -jar StringTruncate.jar
    Exception in thread "main" java.lang.UnsupportedClassVersionError: stringtruncate/StringTruncate : Unsupported major.minor version 52.0
            at java.lang.ClassLoader.defineClass1(Native Method)
            at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
            at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
            at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
            at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
            at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
            at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
            at java.security.AccessController.doPrivileged(Native Method)
            at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
            at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
            at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)

It seems there is a version issue.  Do you know what I should do to get your program to run?  Thanks!

**Comment by d-ying** [comment]
Hi, and sorry for the late response, it's been a very long time since I've been on github...

Based on the error message, your java --version output, and my hazy memory I believed I compiled the jar using jdk (java development version) 1.8 and you are trying to run it using jdk 1.7 which is what is causing the version error.

You can go to http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html to download jdk 1.8. Please let me know if that helps!

**Comment by MareoRaft** [comment]
That works, thanks!
